spring:
  application:
    name: api-gateway
server:
  port: 8701

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: produto-route
          uri: lb://produto-service
          predicates:
            - Path=/produtos/**
        - id: pedido-route
          uri: lb://pedido-service
          predicates:
            - Path=/pedidos/**
